<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*

 REDBANA PHILS PAYROLL 
 For Practicum Purposes | CMSC 198 | summer 2011
 Generated by: Llave, Abraham Darius S. | 2008-37120
 
 FilePurpose: CONTROLLER-WITHOLDINGTAX
 version: 1.0.0
 
 CHANGELOG
 28apr2011 1648h - 1.0.0 - basic basic basic. no mechanism yet for determining if logged in. no form validation.

*/

class witholdingTaxController extends CI_Controller
{
	function __construct()
	{
		parent::__construct();
		$this->load->helper('url');		
	}

	function index()
	{
		if
		(
		 //put logic here in determining if not logged in
		 !true
		)
		{
		
		}else		//user is logged in
		{
			$this->load->model('witholdingTax_model', '', TRUE);			
			$data['details'] = $this->witholdingTax_model->pull_All_Information();			
			$this->load->view('changeWitholdingTaxView', $data);			
		}
	
	}
	
	function editBracket($paymentMode, $bracket)
	{
		if
		(
		 //put logic here in determining if not logged in
		 !true
		)
		{
		
		}else		//user is logged in
		{
			$this->load->model('witholdingTax_model', '', TRUE);
			
			$data['details'] = $this->witholdingTax_model->pull_Single_Info($paymentMode, $bracket);
			$data['paymentMode_info'] = $this->witholdingTax_model->pull_PaymentMode_Info($paymentMode);
			$this->load->view('changeWitholdingTaxProper_View', $data);						
		}
	}
	
	function updateBracket()
	{
		if
		(
		 //put logic here in determining if not logged in
		 !true
		)
		{
		
		}else		//user is logged in
		{
					/*
						FORM VALIDATIONS
					*/
					
					
					$this->load->model('witholdingTax_model');
					$this->witholdingTax_model->updateBracket();					
					$this->index();		// go to list of witholding tax page again.					
		}
	}
}

/* End of file witholdingTaxController.php */
/* Location: ./application/controller/witholdingTaxController.php */
?>