<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*

 REDBANA PHILS PAYROLL 
 For Practicum Purposes | CMSC 198 | summer 2011
 Generated by: Llave, Abraham Darius S. | 2008-37120
 
 FilePurpose: CONTROLLER-WITHOLDINGTAX
 version: 1.0.0
 
 CHANGELOG
 28apr2011 1648h - 1.0.0 - basic basic basic. no mechanism yet for determining if logged in. no form validation.
 ????			 - 1.1.0 - kristine added form validations sa updateBRacket method
 03may2011 1710h - 1.2.0 - now checks if a user is logged in, sa __construct method pa lang. if not, diretso sa login page.

*/

class witholdingTaxController extends CI_Controller
{
	
		
	function __construct()
	{		
		parent::__construct();
		
		$this->load->helper(array('form','url') );		
		$this->load->model('login_model');
		if ( ($this->login_model->isUser_LoggedIn())==FALSE ) 	
		{			
			redirect('login');
		}
		else
		{
			if (($this->login_model->can_Access("wth"))==FALSE)
				redirect('super');
		}
	}
	
	function index()
	{		
			$x; 
			$y;
			$z;			

			//load model(s)
			$this->load->model('witholdingTax_model', '', TRUE);			
							
			//first, we get how many payment modes we are considering.
			$data['payment_modes'] = $this->witholdingTax_model->pull_PaymentInfo();
			
			//for each payment mode, get the corresponding witholding tax charges
			for(  $x = 0, 
				  $y = $data['payment_modes']->num_rows, 
				  $obj = $data['payment_modes']->result(); 
				$x < $y;
				$x++)
			{				
				$data['witholding_tax'][$obj[$x]->TITLE] = $this->witholdingTax_model->pull_per_PaymentMode($obj[$x]->ID);
			}
						
			$this->load->view('changeWitholdingTaxView', $data); //pass it to view
			
	}
	
	function editBracket($paymentMode = -1, $bracket = -1, $showError = false)
	{							
			$this->load->model('witholdingTax_model', '', TRUE);
						
			$data['details'] = $this->witholdingTax_model->pull_Single_Info($paymentMode, $bracket);
			
			
			if( $data['details']->num_rows != 1 )
			{
					/*
						further work: show the user na error yung ininput niya na parameter
					*/
					redirect('/witholdingTaxController');
			}
					
			$data['details'] = $this->witholdingTax_model->pull_Single_Info($paymentMode, $bracket);
			$data['paymentMode_info'] = $this->witholdingTax_model->pull_PaymentMode_Info($paymentMode);			
			$this->load->view('changeWitholdingTaxProper_View', $data);						
	}
	
	function updateBracket()
	{
					//global $errorMsg;
					
					
					/**FORM VALIDATIONS**/
					$this->load->library('form_validation');
					
					/*set validation rules*/
					$this->form_validation->set_rules('exemption_definite','Exemption Definite','numeric','required|greater_than[-2]');
					$this->form_validation->set_rules('exemption_percent','Exemption Percent','numeric','required|greater_than[-2]');
					$this->form_validation->set_rules('a_z','Z','numeric','required|greater_than[0]');
					$this->form_validation->set_rules('a_sme','S/ME','required|greater_than[0]');
					$this->form_validation->set_rules('b_mes1','ME1/S1','numeric','required|greater_than[0]');
					$this->form_validation->set_rules('b_mes2','ME2/S2','numeric','required|greater_than[0]');
					$this->form_validation->set_rules('b_mes3','ME3/S3','numeric','required|greater_than[0]');
					$this->form_validation->set_rules('b_mes4','ME4/S4','numeric','required|greater_than[0]');
					
					if($this->form_validation->run() != FALSE){
						$this->load->model('witholdingTax_model');
						$this->witholdingTax_model->updateBracket();
						
						$this->index();		// go to list of witholding tax page again.
					}else{
						/*
							tell the user of his error.
						*/
																		
						$this->editBracket($this->input->post('payment_mode'), $this->input->post('bracket'), true);												
					}
		
	}
}

/* End of file witholdingTaxController.php */
/* Location: ./application/controller/witholdingTaxController.php */