
<script src="<?php echo base_url();?>devtools/jquery-1.5.2"></script>
<script src="<?php echo base_url();?>devtools/ui/jquery.ui.core.js"></script>
<script src="<?php echo base_url();?>devtools/ui/jquery.ui.widget.js"></script>
<script src="<?php echo base_url();?>devtools/ui/jquery.ui.accordion.js"></script>
<script src="<?php echo base_url();?>devtools/ui/jquery.ui.tabs.js"></script>
<script src="<?php echo base_url();?>devtools/ui/jquery.ui.datepicker.js"></script>