<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*

 REDBANA PHILS PAYROLL 
 For Practicum Purposes | CMSC 198 | summer 2011
 Generated by: Llave, Abraham Darius S. | 2008-37120
 
 FilePurpose: MODEL-WITHOLDINGTAX
 version: 1.0.0 
 
 CHANGE LOG
 28apr2011 - 1.0.0 - basic basic basic

*/

 class witholdingTax_model extends CI_Model
 {
	function __construct()
	{
		parent::__construct();
	}
 
	function pull_All_Information()
	{
		// 27apr2011_2227: change the SQL to the one that conforms to CodeIgniter rules.	
		return $this->db->query("SELECT * FROM `witholding_tax`");
	}
	
	function pull_Single_Info($paymentMode, $bracket)
	{
		$sql_x = "SELECT * FROM `witholding_tax` WHERE PAYMENT_MODE_ID_FK = ? AND BRACKET = ? ";
		return $this->db->query($sql_x, array($paymentMode, $bracket));
	}
	
	function pull_PaymentMode_Info($paymentMode)
	{
		$sql_x = "SELECT * FROM payment_mode where ID = ?";
		return $this->db->query($sql_x, array($paymentMode));
	}
	
	function updateBracket()
	{
		$fields = array(		 						
			"EXEMPTION_DEFINITE",
			"EXEMPTION_PERCENT",
			"A_Z",
			"A_SME",
			"B_MES1",
			"B_MES2",
			"B_MES3",
			"B_MES4"
		);
		foreach($fields as $fields_individual)
		{						
			// Using binds automatically escapes.
			$sql_x = "UPDATE `redbana_payroll`.`witholding_tax` SET {$fields_individual} = ? WHERE `witholding_tax`.`PAYMENT_MODE_ID_FK` = ? AND `witholding_tax`.`BRACKET` = ?";
			
			//now insert to database						
			$this->db->query($sql_x, array($_POST[strtolower($fields_individual)], $_POST['payment_mode'], $_POST['bracket']));						
		}
	}
	
 }

/* End of file witholdingTax_model.php */
/* Location: ./application/model/witholdingTax_model.php */
?>