<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 REDBANA PHILS PAYROLL 
 For Practicum Purposes | CMSC 198 | summer 2011
 Generated by: Llave, Abraham Darius S. | 2008-37120
 
 FilePurpose: VIEW-CHANGE-WITHOLDINGTAX
 version: 1.0.0 - initial work
 		  1.1.0 - changed over-all HTML and structure. more dynamic now.
*/
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
	<title> Edit Witholding Tax - Redbana Phils. Payroll </title>
<style type="text/css">
</style>
<link href="<?php echo base_url(); ?>assets/css/mainstyling.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="header" class="center">
	<img src="<?php echo base_url(); ?>assets/images/payroll.png" alt="header" />
</div>
<div id="header2" class="center">
	<p id="edit"> Edit Witholding Tax </p>
</div>
<div id="header2" class="center">
	<ul class="nav">
		<li class="nav"><a id="nav" href="<?php echo base_url(); ?>"> Home </a></li>
	</ul>
<?php 
	echo "<a class='active' href='login/logout' id='cname' alignment='left' > Sign out </a>";				
?>
</div>
<div id="container" class="center">
	To edit, click the bracket number located within the payperiod concerned.
<br /><br /><br />
	<?php
		$x; $a; $bracket_objs;
		$y; $b;
		$z; $c;
		
		$x_1; $a_1; $bracket_objs_1;
		$y_1; $b_1;
		$z_1; $c_1;
		
		for( $x=0, $y = $payment_modes->num_rows, $this_obj = $payment_modes->result();
			 $x < $y;
			 $x++)
		{			
		?>
			<div  class="witholdingTax_description">
				<div class="payment_mode_title" ><?php echo $this_obj[$x]->TITLE; ?></div> <br />
				<span> Exemption </span><br />				
				<span> Status </span><br />				
			</div>	
			<?php
				$bracket_objs = $witholding_tax[$this_obj[$x]->TITLE]->result();
				$b = $witholding_tax[$this_obj[$x]->TITLE]->num_rows;
				for($a = 0; $a < $b; $a++)
				{				
				 		
			?>
				<div class="witholdingTax_data">
					<div class="payment_mode_title">
						<a href="
						<?php 
							echo base_url()."index.php"."/witholdingTaxController/editBracket/".$this_obj[$x]->ID."/".$bracket_objs[$a]->BRACKET;
						?> 
						"><?php echo $bracket_objs[$a]->BRACKET;  ?></a>
					</div><br />
					<span><?php echo $bracket_objs[$a]->EXEMPTION_DEFINITE; ?> </span><br />
					<span><?php echo $bracket_objs[$a]->EXEMPTION_PERCENT; ?> </span><br />
					
				</div>				
			 
			<?php
				}
			?>	
			<br /><br /><br />
			<div id="payment_mode_subdivide" >
					A. Table for employees without qualified dependent
			</div>
				<?php
		
		{			
		?>
			<div  class="witholdingTax_description">
				<span>1. Z</span><br />				
				<span>2. S/ME</span><br />				
			</div>	
			<?php
				$bracket_objs_1 = $witholding_tax[$this_obj[$x]->TITLE]->result();
				$b_1 = $witholding_tax[$this_obj[$x]->TITLE]->num_rows;
				for($a_1 = 0; $a_1 < $b_1; $a_1++)
				{								 		
			?>
				<div class="witholdingTax_data">					
					<span><?php echo $bracket_objs[$a_1]->A_Z; ?> </span><br />
					<span><?php echo $bracket_objs[$a_1]->A_SME; ?> </span><br />					
				</div>				
			 
			<?php
				}
			?>	
			<div id="payment_mode_subdivide" >
			B. Table for single/married employee with qualified/dependent child(ren)
			</div>
			<div  class="witholdingTax_description">
				<span>1. ME1/S1</span><br />				
				<span>2. ME2/S2</span><br />				
				<span>3. ME3/S3</span><br />				
				<span>4. ME4/S4</span><br />				
			</div>	
			<?php
				$bracket_objs_1 = $witholding_tax[$this_obj[$x]->TITLE]->result();
				$b_1 = $witholding_tax[$this_obj[$x]->TITLE]->num_rows;
				for($a_1 = 0; $a_1 < $b_1; $a_1++)
				{								 		
			?>
				<div class="witholdingTax_data">					
					<span><?php echo $bracket_objs[$a_1]->B_MES1; ?> </span><br />
					<span><?php echo $bracket_objs[$a_1]->B_MES2; ?> </span><br />
					<span><?php echo $bracket_objs[$a_1]->B_MES3; ?> </span><br />
					<span><?php echo $bracket_objs[$a_1]->B_MES4; ?> </span><br />					
				</div>					 
			<?php
				}
			?>	
<br /><br /><br />			
<?php	
		}
?>
<?php		
		}
?>
</div>
<div id="copyright" >
<p>Copyright 2011 | Bautista and Associates Information Systems</p>
</div>
</body>
</html>