<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*

 REDBANA PHILS PAYROLL 
 For Practicum Purposes | CMSC 198 | summer 2011
 Generated by: Llave, Abraham Darius S. | 2008-37120
 
 FilePurpose: VIEW-PAYPERIOD-FINALIZECONFIRM
 version: 1.0.0 - initial work
 		 
*/


?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<title>Result of Finalization of PayPeriod - Redbana Phils. Payroll</title>
<style type="text/css">
</style><link href="<?php echo base_url(); ?>assets/css/mainstyling.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="header" class="center">
	<img src="<?php echo base_url(); ?>assets/images/payroll.png"  alt="header" />
</div>
<div id="header2" class="center">
	<ul class="nav">
		<li class="nav"><a id="nav" href="<?php echo base_url(); ?>">Home</a></li>
	</ul>
</div>
<div id="container" class="center" >
	<div id="article_SpecificDetail" class="center" style="width:80%">
	<?php
		if($result)
			echo "Success";
		else
			echo "EPIC FAIL!";
	?>
	</div>
	<div class="center" style="width:80%">
		
			<?php
			if($result)
				echo "The payperiod has been finalized.";
			else{
				echo '<div id="form_error_notice" style="width: 80%" class="center"><br/>';
				echo "Sorry, something went wrong during finalization. Please try again.";
				echo '</div>';
			}
			?>
		<div>					
				<ul style="list-style-type:none; margin-top:15px; text-align:center">
					<li>
						<?php
							echo '<a href="'.base_url().'index.php/AttendanceController" >'.form_button('meowx', 'Go back to Attendance Fault Center').'</a>';
						?>
					</li>
				</ul>		
		</div>
	 </div>
</div>
<div id="copyright" >
<p>Copyright 2011 | Bautista and Associates Information Systems</p>
</div>

</body>

</html>


