<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*

 REDBANA PHILS PAYROLL 
 For Practicum Purposes | CMSC 198 | summer 2011
 Generated by: Llave, Abraham Darius S. | 2008-37120
 
 FilePurpose: VIEW-PAYPERIOD-DISPLAYANOMALIES
 version: 1.0.0 - initial work
 		 
*/


?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<title>Anomalies upon Finalization try - Redbana Phils. Payroll</title>
<style type="text/css">
</style><link href="<?php echo base_url(); ?>assets/css/mainstyling.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="header" class="center">
	<img src="<?php echo base_url(); ?>assets/images/payroll.png"  alt="header" />
</div>
<div id="header2" class="center">
	<ul class="nav">
		<li class="nav"><a id="nav" href="<?php echo base_url(); ?>">Home</a></li>
	</ul>
</div>
<div id="container" class="center" >
<div id="article_SpecificDetail" class="center" style="width:80%">
	Finalization - Anomalies
</div>
<div class="center" style="width:80%">
	We regret to inform you that you cannot finalize for this payperiod directly.<br/>
	Please review the messages reported and take appropriate action before deciding if you want to finalize.<br/><br/>
	<?php
		
				
		echo '<div id="form_error_notice" style="width: 80%" class="center"><br/>';
		
		if( !empty($missing_in_TimeSheet) )
		{
			echo "<strong> -> NO TIMESHEET ENTRY FROM ({$payperiod_obj->START_DATE}) - ({$payperiod_obj->END_DATE})</strong>";
			echo "<ul>";
			foreach($missing_in_TimeSheet as $emp_missing)
			{
				echo "<li>{$emp_missing}&nbsp;&nbsp;|&nbsp;&nbsp;{$eligible_employees[$emp_missing]->sname},&nbsp;{$eligible_employees[$emp_missing]->fname}&nbsp;&nbsp;{$eligible_employees[$emp_missing]->mname}</li>";				
			}		    
			
			echo "</ul>";	
			echo "<br/>";
			if($payperiod_lapsed) echo "<strong> -> TODAY IS STILL PART OF THE CURRENT PAYPERIOD</strong>";		
			echo "<br/><br/>";

		}		
	    echo '</div>';
	?>
	<?php
		echo '<br/><br/>';
		echo form_open('PayperiodController/finalizePayPeriod_askConfirmation');
		echo form_hidden('PAYPERIOD', $payperiod_obj->ID);	
		echo form_hidden('PAYMENT_MODE', $payment_mode);
		echo '<a href="'.base_url().'index.php/AttendanceController" >'.form_button('meowx', 'Go back').'</a>';
		echo form_submit('mysubmit','Finalize Anyway'); 
		echo form_close();
	?>
</div>
</div>
<div id="copyright" >
<p>Copyright 2011 | Bautista and Associates Information Systems</p>
</div>

</body>

</html>

