<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*

 REDBANA PHILS PAYROLL 
 For Practicum Purposes | CMSC 198 | summer 2011
 Generated by: Llave, Abraham Darius S. | 2008-37120
 
 FilePurpose: VIEW-GENERATEATTENDACEFAULT-RESULT
 version: 1.0.0 - initial work
 		 
*/


?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<title>View Attendance Fault Data - Redbana Phils. Payroll</title>
<style type="text/css">
</style><link href="<?php echo base_url(); ?>assets/css/mainstyling.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="header" class="center">
	<img src="<?php echo base_url(); ?>assets/images/payroll.png"  alt="header" />
</div>
<div id="header2" class="center">
	<ul class="nav">
		<li class="nav"><a id="nav" href="<?php echo base_url(); ?>">Home</a></li>
	</ul>
</div>
<div id="container" class="center" >
	<div id="article_SpecificDetail" class="center" >
		View Attendance Faults for This Pay Period (<?php echo $payperiod_obj->START_DATE." - ".$payperiod_obj->END_DATE;  ?>)
	</div>
	<div class="center" >
		<?php
			if( empty($result) )
			{
				echo "No data yet for this Pay Period and Payment Mode.<br/><br>";
				echo "Go back to home and click Generate.<br/>";				
			}else
			{
				echo "<strong>Statistics<strong>";
		?>
				<table border="1">
					<thead>
						<tr>
							<th>Name</th>							
							<th>Total</th>
						</tr>
					</thead>
					<tbody>
					 <?php foreach($statistics as $each_statistic)  
							{						 	
					 ?>
						<tr>
							<td><?php echo $each_statistic['title']; ?></td>
							<td><?php echo $each_statistic['value']; ?></td>
						</tr>
					<?php	}
					?>
					
					</tbody>
				</table>
				<br/><br/>
				<strong>Each Employee Data</strong>
				<table border="1">
					<thead>
						<tr>
							<th>EmpNum</th>							
							<th>Name</th>
							<th>Monthly Rate</th>
							<th>Daily Rate</th>
							<th>Days - Absences &amp; Lwop</th>
							<th>Amount - Absences &amp; Lwop</th>
							<th>Days - Sick &amp; Leave</th>
							<th>Amount - Sick &amp; Leave</th>
							<th>Days - Suspension</th>
							<th>Amount - Suspension</th>
							<th>Minutes - Tardiness</th>
							<th>Amount - Tardiness</th>
							<th>Total Amount</th>
							<th>Paid VL days</th>
							<th>Paid SL days</th>
							<th>Paid Emergency Leave Days</th>
							<th>Generated</th>
							<th>Modified by</th>					
						</tr>
					</thead>
					<tbody>
					 <?php foreach($result as $each_employee)  
							{						 	
					 ?>
						<tr>
							<td><?php echo $each_employee->empnum; ?></td>	
							<td>COMING SOON</td>						
							<td><?php echo $each_employee->monthly_rate; ?></td>
							<td><?php echo $each_employee->daily_rate; ?></td>
							<td><?php echo $each_employee->absences_lwop_days; ?></td>
							<td><?php echo $each_employee->absences_lwop_amount; ?></td>
							<td><?php echo $each_employee->leave_sick_vacation_days; ?></td>
							<td><?php echo $each_employee->leave_sick_vacation_amount; ?></td>
							<td><?php echo $each_employee->suspension_days; ?></td>
							<td><?php echo $each_employee->suspension_amount; ?></td>
							<td><?php echo $each_employee->tardiness_min; ?></td>
							<td><?php echo $each_employee->tardiness_amount; ?></td>
							<td><?php echo $each_employee->total_amount; ?></td>
							<td><?php echo $each_employee->paid_vl_days; ?></td>
							<td><?php echo $each_employee->paid_sl_days; ?></td>		
							<td><?php echo $each_employee->paid_emergency_leave_days; ?></td>
							<td><?php echo $each_employee->last_update; ?></td>
							<td><?php echo $each_employee->modified_by; ?></td>

						</tr>
					<?php	}
					?>
					
					</tbody>
				</table>
				<br/><br/>
		<?php
			}			
		echo '<a href="'.base_url().'index.php/AttendanceController" >'.form_button('meowx', 'Go back to Attendance Fault Center').'</a>';
		?>		
	 </div>
	 <br/>
</div>
<div id="copyright" >
<p>Copyright 2011 | Bautista and Associates Information Systems</p>
</div>

</body>

</html>


