<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 REDBANA PHILS PAYROLL 
 For Practicum Purposes | CMSC 198 | summer 2011
 Generated by: Llave, Abraham Darius S. | 2008-37120
 
 FilePurpose: VIEW-NOTICE-ATTENDANCEFAULT-CANNOTFINDDATE-IN-PAYERIOD
 version: 1.0.0 - initial work		 
*/
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
	<title> Error - Redbana Phils. Payroll </title>
<style type="text/css">
</style>
<link href="<?php echo base_url(); ?>assets/css/mainstyling.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="header" class="center">
	<img src="<?php echo base_url(); ?>assets/images/payroll.png" alt="header" />
</div>
<div id="header2" class="center">
	<ul class="nav">
		<li class="nav"><a id="nav" href="<?php echo base_url(); ?>"> Home </a></li>
	</ul>
<?php 
	echo "<a class='active' href='login/logout' id='cname' alignment='left' > Sign out </a>";				
?>
</div>
<div id="container" class="center">
<div id="article_SpecificDetail" class="center" style="width:80%"> Payperiod Controversy
</div>
<div class="center" style="width:80%">
	To generate Attendace Faults (Tardiness, Abesences, etc.), we need to know which dates
	you are concerned with. By default, this application looks at the current date of the server
	and looks on its record of 'PayPeriods' to further process the generating of Attendance Faults.
	However, the current date today (<?php echo $date_today; ?>) does not match any of the entries in
	the Payperiod database.
	<br /><br /><br />
	Please check if the date and time on this server are correct, and set it to the correct one if wrong.
	<br /><br />	
	Or
	<br /><br />
	<a href="<?php echo site_url().'/PayPeriodController/addPayPeriod' ?>"> Generate a new PayPeriod. </a>
	<?php 
		if($lastPayPeriod != NULL)
		{
	?>	
	<br /><br /> or <br /><br />
		<a href="<?php echo site_url().'/AttendanceController/regenerateAttendanceFaultData/'.$lastPayPeriod->ID; ?>">
		Regenerate Attendance Faults for previous (Semi-Monthly) PayPeriod. </a> 
		( <?php echo $lastPayPeriod->START_DATE; ?> - <?php echo $lastPayPeriod->END_DATE; ?> )
		<br />
	<?php
		}
	?>
	<br />
</div>
</div>
<div id="copyright">
<p> Copyright 2011 | Bautista and Associates Information Systems </p>
</div>
</body>
</html>