<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 REDBANA PHILS PAYROLL 
 For Practicum Purposes | CMSC 198 | summer 2011
 Generated by: Llave, Abraham Darius S. | 2008-37120
 
 FilePurpose: VIEW-CHANGE-WITHOLDINGTAXWITHINPUTBOX
 version: 1.0.0 - initial work
 		  1.1.0 - changed over-all HTML and structure. more dynamic now.
*/
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
	<title> Edit Witholding Tax - Redbana Phils. Payroll </title>
<style type="text/css">
li
{
	float: left;	
}
li.descriptor
{
	width: 40%;
	clear: left;
	overflow: auto;
	
}
}
</style>
<link href="<?php echo base_url(); ?>assets/css/mainstyling.css" rel="stylesheet" type="text/css" />
</head>

<body>
<?php
	$x = $paymentMode_info->row();				
	$bracket_Detail_Local = $details->row();
?>
<div id="header" class="center">
	<img src="<?php echo base_url(); ?>assets/images/payroll.png"  alt="header" />
</div>
<div id="header2" class="center">
	<p id="edit"> Edit Witholding Tax Bracket </p>
</div>
<div id="header2" class="center">
	<ul class="nav">
		<li class="nav"><a id="nav" href="<?php echo base_url(); ?>"> Home </a></li>
	</ul>
<?php 
	echo "<a class='active' href='login/logout' id='cname' alignment='left' > Sign out </a>";				
?>	
</div>
<div id="container" class="center">
	<form>
	<!--<form name="witholding_tax_bracket" action="<?php echo site_url(); ?>/witholdingTaxController/updateBracket" method="post">
	-->
	<?php echo form_open('witholdingTaxController/updateBracket'); ?>
	<input type="hidden" name="payment_mode" value="<?php echo $x->ID; ?>" />
	<input type="hidden" name="bracket" value="<?php echo $bracket_Detail_Local->BRACKET; ?>" />
	<div id="article_SpecificDetail" class="center">
		<?php
			echo "PAYMENT MODE: ".$x->TITLE."<br />";				
			echo "BRACKET: ".$bracket_Detail_Local->BRACKET."<br />";								
		?>	
	</div>	
	<?php		
		if(strlen(validation_errors()) != 0 )
		{
			echo '<div id="form_error_notice" class="center" style="width: 80%; border-color: red"><br />';
			echo '!! ERROR <br />';	
			echo validation_errors();		
			echo '<br /></div><br />';	
		}
	?>	
	<div  class="center" style="width:80%">
		<ul style="list-style-type: none; font-size: 1.4em">
			<li class="descriptor"> Exemption Definite: </li>
		 	<li>	
		 			<?php echo form_error('EXEMPTION_DEFINITE'); ?>
					<input type="text" class="numeric" name="exemption_definite" id="exemption_definite" 
			value="<?php
					/*echo var_dump(set_value('EXEMPTION_DEFINITE'));
					if(strlen(validation_errors()) != 0){
						set_value('EXEMPTION_DEFINITE');
					}
					else{*/
			      		echo $bracket_Detail_Local->EXEMPTION_DEFINITE;
			      	//}
			      ?>"/>
		
			</li>
			<li class="descriptor"> Exemption Percent: </li>
		 	<li>		
					<input type="text" class="numeric" name="exemption_percent" id="exemption_percent" 
			value="<?php
			      	echo $bracket_Detail_Local->EXEMPTION_PERCENT;
			      ?>" />
		
			</li>			
		</ul>
	</div>
	<div id="payment_mode_subdivide_witholdingTaxEditProper" class="center">
			A. Table for employees without qualified dependent
	</div>
	<div class="center" style="width:80%">
		<ul style="list-style-type: none; font-size: 1.4em">
			<li class="descriptor"> 1. Z </li>
		 	<li>		
					<input type="text" class="numeric" name="a_z" id="a_z"
					value="<?php
					      	echo $bracket_Detail_Local->A_Z;
					      ?>" />		
			</li>
			<li class="descriptor"> 2. S/ME </li>
		 	<li>		
					<input type="text" class="numeric" name="a_sme" id="a_sme"
					value="<?php
					      	echo $bracket_Detail_Local->A_SME;
					      ?>" />		
			</li>			
		</ul>
	</div>
	<div id="payment_mode_subdivide_witholdingTaxEditProper" class="center">
			B. Table for single/married employee with qualified/dependent child(ren) 
	</div>
	<div  class="center" style="width:80%">
		<ul style="list-style-type: none; font-size: 1.4em">
			<li class="descriptor"> 1. ME1/S1 </li>
		 	<li>		
					<input type="text" class="numeric" name="b_mes1" id="b_mes1" 
					value="<?php
					      	echo $bracket_Detail_Local->B_MES1;
					      ?>" />		
			</li>
			<li class="descriptor"> 2. ME2/S2 </li>
		 	<li>		
					<input type="text" class="numeric" name="b_mes2" id="b_mes2" 
					value="<?php
					      	echo $bracket_Detail_Local->B_MES2;
					      ?>" />		
			</li>		
			<li class="descriptor"> 3. ME3/S3 </li>
		 	<li>		
					<input type="text" class="numeric" name="b_mes3" id="b_mes3"
					value="<?php
					      	echo $bracket_Detail_Local->B_MES3;
					      ?>" />		
			</li>		
			<li class="descriptor"> 4. ME4/S4 </li>
		 	<li>		
					<input type="text" class="numeric" name="b_mes4" id="b_mes4"
					value="<?php
					      	echo $bracket_Detail_Local->B_MES4;
					      ?>" />		
			</li>									
		</ul>
	</div>
	<div  class="center" style="width:80%; clear: left; padding-top: 10px;">
		<ul style="list-style-type: none; font-size: 1.4em">
			<li><input type="submit" value="Change Values" /></li>
		 	<li><input type="reset" /><br /></li>			
		 	<li>		
				<a href="<?php echo site_url(); ?>/witholdingTaxController/" ><input type="button" value="Go back" /></a>
			</li>						
		</ul>
	</div>
	</form>
</div>
<div id="copyright" >
<p> Copyright 2011 | Bautista and Associates Information Systems </p>
</div>
</body>
</html>