<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*

 REDBANA PHILS PAYROLL 
 For Practicum Purposes | CMSC 198 | summer 2011
 Generated by: Llave, Abraham Darius S. | 2008-37120
 
 FilePurpose: VIEW-CHANGE-WITHOLDINGTAXWITHINPUTBOX
 version: 1.0.0

*/



?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<title>Edit Witholding Tax</title>

<style type="text/css">
#eventTitle {
	font-family: Arial, Helvetica, sans-serif;
	font-size: xx-large;
	font-weight: bold;
	font-style: normal;
	color: #008000;
	text-align: left;
	border: thin solid #000099;
	width: 944px;
	height: 50px;
	background-repeat: repeat-x;
	background-attachment: fixed;
	vertical-align: text-bottom;
	overflow: hidden;
	margin: 0px;
	padding: 0px;
	word-spacing: 0em;
	background-image: url('images/event-bg3.png');
}

#menuSub-Bar {
	font-family: Arial, Helvetica, sans-serif;
	font-size: x-small;
	font-weight: normal;
	font-style: normal;
	color: #000000;
	text-align: left;
	border: thin solid #000099;
	width: 944px;
	height: 25px;
	background-repeat: repeat-x;
	background-attachment: fixed;
	vertical-align: middle;
	overflow: hidden;
	margin: 0px;
	padding: 0px;
	word-spacing: 0em;
	background-image: url('images/event-bg3.png');
}

#main_div {
	font-family: Arial, Helvetica, sans-serif;
	font-size: x-small;
	font-weight: normal;
	font-style: normal;
	color: #000000;
	text-align: left;
	border: thin solid #000000;
	width: 944px;
	background-repeat: repeat-x;
	background-attachment: fixed;
	vertical-align: middle;
	overflow: hidden;
	margin: 0px 0px 5px 0px;
	padding: 0px 0px 10px 0px;
	word-spacing: 0em;
}

#UPDATE_MESSAGE {
	font-family: Arial, Helvetica, sans-serif;
	font-size: small;
	font-weight: bold;
	width: 944px;
	color: #333333;
	background-color: #E8F8FF;
	text-align: center;
}
#payment_mode_title {
	font-family: Arial, Helvetica, sans-serif;
	font-size: x-small;
	background-color: #18DCE7;
	font-weight: bold;
	visibility: visible;
	float: left;
	clear: both;
	display: block;
	width: 912px;
}
.bracketSpan {
	width: 80px;
	margin-left: 2px;
	margin-right: 2px;
	text-align: center;
	float: left;
	position: relative;
}
.paymentMode_propertitle {
	width: 138px;
	text-align: center;
	float: left;
}
.contentDiv {
	font-family: Arial, Helvetica, sans-serif;
	font-size: x-small;
	position: relative;
}
.paymentMode_propertitle_alternate {
	width: 142px;
	text-align: center;
	float: left;
}
#payment_mode_subdivide {
	font-family: Arial, Helvetica, sans-serif;
	font-size: x-small;
	background-color: #999999;
	visibility: visible;
	float: left;
	clear: both;
	display: block;
	width: 912px;
}
.main_Fieldbox_descriptor {
	float: left;
	font-size: medium;
	height: 28px;
	vertical-align: inherit;
	margin-left: 250px;
	width: 154px;
	text-align: left;
}
.main_Fieldbox_value {
	height: 28px;
	vertical-align: super;
	padding-bottom: 3px;
	text-align: left;
	padding-left: 39px;
	float: left;
}
.fields {
	height: 17px;
}
.buttonCollection {
	float: left;
	visibility: visible;
	margin-left: 350px;
}
.bracketHeader {
	font-size: large;
	margin-left: 50px;
}
</style>
</head>


<body >
<center>
 


<div id="eventTitle"> 
	&nbsp; REDBANA PAYROLL 
	- WITHOLDING TAX</div>
<div id="menuSub-Bar">
	&nbsp;&nbsp;%% DIsplay date of effectivity here as per BIR
</div>

<div id="main_div">
	<div class="bracketHeader" >
		<span>
			<?php
				$x = $paymentMode_info->row();				
				$bracket_Detail_Local = $details->row();
				echo "PAYMENT MODE: ".$x->TITLE."<br/>";				
				echo "BRACKET: ".$bracket_Detail_Local->BRACKET."<br/>";								
			?>				
		</span>		
	</div>
		
	<center>
	<form name="witholding_tax_bracket" action="<?php echo site_url(); ?>/witholdingTaxController/updateBracket" method="post">
	<input type="hidden" name="payment_mode" value="<?php echo $x->ID; ?>" />
	<input type="hidden" name="bracket" value="<?php echo $bracket_Detail_Local->BRACKET; ?>" />
	<div class="main_Fieldbox">	
		<div class="main_Fieldbox_descriptor">
			Exemption Definite:
		</div>
		<div class="main_Fieldbox_value" >
			<input type="text" name="exemption_definite" 
			value="<?php
			      	echo $bracket_Detail_Local->EXEMPTION_DEFINITE;
			      ?>" />
		</div>
		<br/>
		<div class="main_Fieldbox_descriptor">
			Exemption Percent:
		</div>
		<div class="main_Fieldbox_value" >
			<input type="text" name="exemption_percent" 
			value="<?php
			      	echo $bracket_Detail_Local->EXEMPTION_PERCENT;
			      ?>" />
		</div>		
		<div id="payment_mode_subdivide" >
			A. Table for employees without qualified dependent
		</div>
		<br/><br/><br/><br/><br/><br/>
		<div class="main_Fieldbox_descriptor">
			1. Z
		</div>
		<div class="main_Fieldbox_value" >
			<input type="text" name="stat_a_z" 
			value="<?php
			      	echo $bracket_Detail_Local->STAT_A_Z;
			      ?>" />
		</div>		
		<br/>
		<div class="main_Fieldbox_descriptor">
			2. S/ME
		</div>
		<div class="main_Fieldbox_value" >
			<input type="text" name="stat_a_sme" 
			value="<?php
			      	echo $bracket_Detail_Local->STAT_A_SME;
			      ?>" />
		</div>		
		<div id="payment_mode_subdivide" >
			B. Table for single/married employee with qualified/dependent child(ren) 
		</div>
		<br/><br/><br/><br/><br/><br/>
		<div class="main_Fieldbox_descriptor">
			1. ME1/S1
		</div>
		<div class="main_Fieldbox_value" >
			<input type="text" name="stat_b_mes1" 
			value="<?php
			      	echo $bracket_Detail_Local->STAT_B_MES1;
			      ?>" />
		</div>	
		<div class="main_Fieldbox_descriptor">
			2. ME2/S2
		</div>
		<div class="main_Fieldbox_value" >
			<input type="text" name="stat_b_mes2" 
			value="<?php
			      	echo $bracket_Detail_Local->STAT_B_MES2;
			      ?>" />
		</div>	
		<div class="main_Fieldbox_descriptor">
			3. ME3/S3
		</div>
		<div class="main_Fieldbox_value" >
			<input type="text" name="stat_b_mes3" 
			value="<?php
			      	echo $bracket_Detail_Local->STAT_B_MES3;
			      ?>" />
		</div>	
		<div class="main_Fieldbox_descriptor">
			4. ME4/S4
		</div>
		<div class="main_Fieldbox_value" >
			<input type="text" name="stat_b_mes4" 
			value="<?php
			      	echo $bracket_Detail_Local->STAT_B_MES4;
			      ?>" />
		</div>		
		<div class="buttonCollection" >
			<input type="submit" value="Change Values" />			
			<input type="reset" /><br/>
			<a href="<?php echo site_url(); ?>/witholdingTaxController/" >Back</a>
		</div>		
	</div>
	</form>
	</center>			
</div>
<!-- end of main div -->
<div id="UPDATE_MESSAGE">
<a name="bottom" >Copyright Notice</a>
</div>
</center>
</body>


</html>
<!--
/* End of file changeWitholdingTaxWithInputBox_View.php */
/* Location: ./application/views/changeWitholdingTaxWithInputBox_View.php */
-->