<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!--

 REDBANA PHILS PAYROLL 
 For Practicum Purposes | CMSC 198 | summer 2011
 Generated by: Llave, Abraham Darius S. | 2008-37120
 
 FilePurpose: VIEW-CHANGE-WITHOLDINGTAXWITHINPUTBOX
 version: 1.0.0 - initial work
 		  1.1.0 - changed over-all HTML and structure. more dynamic now.
		  2.0.0 - abe - final design
-->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Home - SuperUser - Redbana Phils. Payroll</title>
<?php $this->load->view('include/css.inc'); ?>
<?php $this->load->view('include/jquery-abe.inc'); ?>
<?php $this->load->view('include/jquery-abe-on_run.inc'); ?>
</head>

<body>
<div id="main_container">
	<div id="header">
    	<div id="logo">
    	<a href="home.html"><img src="<?php echo base_url(); ?>assets/images/redbana_logo2.png" alt="" title="" style="border:0" /></a>    	
    	</div>
    	<div id="logo">
    	<a href="home.html"><img src="<?php echo base_url(); ?>assets/images/payroll_logo.jpg" alt="" title="" style="border:0" /></a>    	
    	</div>
        
         <div id="menu">
            <ul>                                        
                <li><a class="current" href="home.html" title="">Home</a></li>
				<li><a href="#" title="">My Account</a></li>
                <li><a href="#" title="">Edit Other Accounts</a></li>
                <li><a href="contact.html" title="">menu4</a></li>
            </ul>
        </div>
		<div id="graynavbar" >
			
			<ul>
				<li><?php echo $userData['empNum']; ?></li>
				<li><?php echo $userData['fname']." ".$userData['mname']."&nbsp;".$userData['sname']; ?></li>
				<li class="last">
					<a href='login/logout' class='underline'>Log out</a>
				</li>
			</ul>			
		</div>
        
    </div>
    
    <!--end of green box-->
    
    <div id="main_content">    	
    	<div id="centralContainer">
            <div id="demo">
				<div id="accordion">
					<h3><a class="title" href="#">Employees' Corner</a></h3>
					<div class="content" >
						<ul>
							<li>Add Employee</li>
							<li>Edit Employee Info</li>
							<li>View All Employee</li>
							<li>Search Employee</li>
						</ul>
					</div>
					<h3><a class="title" href="#">Classification Maintenances</a></h3>
					<div class="content" >
						<ul>
							<li>Position</li>
							<li>Tax Status</li>
							<li>User right</li>
							<li>Type of Day</li>
							<li>Shift</li>
							<li>Department</li>
							<li>Employment Type</li>								
						</ul>
					</div>
					<h3><a class="title" href="#">Timekeeping</a></h3>
					<div class="content" >			
						<ul>
							<li>View Timesheet</li>			
						</ul>
					</div>
					<h3><a class="title" href="#">Payroll Generation</a></h3>
					<div class="content" >
						<ul>
							<li>View Tardiness/Absences/etc and corresponding charges</li>
							<li>Add new Payperiod</li>
							<li>Generate Payroll </li>
						</ul>
					</div>
					<h3><a class="title" href="#">History</a></h3>
					<div class="content" >
						<ul>				
							<li>View History</li>
						</ul>
					</div>
				</div>
				</div><!-- div#demo -->
        </div><!--end of centralContainer-->
    <div style=" clear:both;"></div>
    </div><!--end of main content-->
 

     <div id="footer">
     	<div class="copyright">
			2011 UPLB Students
        </div>
    	<div class="footer_links"> 
        <a href="#">About us</a>
         <a href="privacy.html">Privacy policy</a> 
        <a href="contact.html">Contact us </a>        
        </div>        
    </div>     
<!--end of main container-->
</body>
</html>
