<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*

 REDBANA PHILS PAYROLL 
 For Practicum Purposes | CMSC 198 | summer 2011
 Generated by: Llave, Abraham Darius S. | 2008-37120
 
 FilePurpose: VIEW-CHANGE-WITHOLDINGTAXWITHINPUTBOX
 version: 1.0.0 - initial work
 		  1.1.0 - changed over-all HTML and structure. more dynamic now.
*/


?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<title>Home - SuperUser - Redbana Phils. Payroll</title>
<style type="text/css">
ul
{
list-style-type:none;
margin-left: 33%;
padding:0;
overflow:hidden;
}
li
{
  float:left;
  clear: left;
  width: 100px;
}
a:link,a:visited
{
display:block;
width:300px;
font-weight:bold;
color:#FFFFFF;
background-color:#98bf21;
text-align:center;
padding:4px;
text-decoration:none;
text-transform:uppercase;
}
a:hover,a:active
{
background-color:#7A991A;
}

</style><link href="<?php echo base_url(); ?>assets/css/mainstyling.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="header" class="center">
	<img src="<?php echo base_url(); ?>assets/images/payroll.png"  alt="header" />
</div>
<div id="header2" class="center">
	<p id="whatareyoudoing">Welcome 
		<?php
			echo $userData['empNum']."&nbsp;|&nbsp;".$userData['fname']." ".$userData['mname']."&nbsp;".$userData['sname']." ! ";
			function can_Access($type,$query)
			{
				$result=false;
				foreach ($query->result() as $row)
				{
					if (($row->privilege ==$type) &&($row->type==1) )
					{
						$result=true;
						break;
					}
				}
				return $result;
			}
		?>		
	</p>
</div>
<!--
<div id="header2" class="center">
	<ul class="nav">
		<li class="nav"><a id="nav" href="<?php echo base_url(); ?>">Home</a></li>
	</ul>
</div>-->
<div id="container" class="center" >
<div id="article_SpecificDetail" class="center" style="width:80%">
	 Activities
</div>
<div style="width:80%" class="center">
	<?php
		echo "<ul>";
		if (can_Access("addemp",$sql))
			echo "<li><a href='employee/insert' class='underline'>Add and Edit Employee Information</a></li>";
		if (can_Access("viewemp",$sql))
			echo "<li><a href='employee/getall' class='underline'>View All Employee</a></li>";
		echo "</ul><ul>";
		if (can_Access("sss",$sql))
			echo "<li><a href='sss/getall' class='underline'>SSS Table</a></li>";
		if (can_Access("phil",$sql))
			echo "<li><a href='philhealth/getall' class='underline'>Philhealth Table</a></li>";
		if (can_Access("wth",$sql))
			echo "<li><a href='witholdingtaxcontroller' class='underline'>Withholding Tax Table</a></li>";
		if (can_Access("position",$sql))
			echo "<li><a href='maintenance/posview' class='underline'>Position Maintenance</a></li>";
		if (can_Access("taxstatus",$sql))
			echo "<li><a href='maintenance/taxview' class='underline'>Tax Status Maintenance</a></li>";
		if (can_Access("user",$sql))
			echo "<li><a href='maintenance/userview' class='underline'>User Right Maintenance</a></li>";
		if (can_Access("day",$sql))
			echo "<li><a href='maintenance/dayview' class='underline'>Type Of Day Maintenance</a></li>";
		if (can_Access("shift",$sql))
			echo "<li><a href='' class='underline'>Shift Maintenance</a></li>";
		if (can_Access("dept",$sql))
			echo "<li><a href='maintenance/deptview' class='underline'>Department Maintenance</a></li>";
		if (can_Access("type",$sql))
			echo "<li><a href='maintenance/typeview' class='underline'>Employment Type Maintenance</a></li>";
		echo "</ul><ul>";
		if (can_Access("allleave",$sql))
			echo "<li><a href='leave/viewall' class='underline'>View All Leave and Approve</a></li>";
		if (can_Access("history",$sql))
			echo "<li><a href='history/getall' class='underline'>View History</a></li>";
		if (can_Access("viewpay",$sql))
			echo "<li><a href='payroll/payrollinfoview' class='underline'>View Payroll</a></li>";
		if (can_Access("viewslip",$sql))
			echo "<li><a href='payroll/individualpayslip' class='underline'>View Your Pay Slip</a></li>";
		echo "</ul><ul>";
		if (can_Access("leave",$sql))
		{
			echo "<li><a href='leave/insert' class='underline'>File a leave</a></li>";
			echo "<li><a href='leave/empview' class='underline'>View all your filed leave</a></li>";
		}
		echo "</ul><ul>";
		if (can_Access("timesheet",$sql))
		{
			echo "<li><a href='timesheet/viewtimesheet' class='underline'>View TimeSheet</a></li>";
			echo "<li><a href='AttendanceController' class='underline'>Absences and Tardiness</a></li>";
		}
		echo "</ul>";
		echo "<ul><li><a href='login/logout' class='underline'>Sign out</a></li></ul>";
	?>
</div>
</div>
<div id="copyright" >
<p>Copyright 2011 | UPLB Students</p>
</div>

</body>

</html>
