<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*

 REDBANA PHILS PAYROLL 
 For Practicum Purposes | CMSC 198 | summer 2011
 Generated by: Llave, Abraham Darius S. | 2008-37120
 
 FilePurpose: VIEW-CHANGE-WITHOLDINGTAXWITHINPUTBOX
 version: 1.0.0 - initial work
 		  1.1.0 - changed over-all HTML and structure. more dynamic now.
*/


?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<title>Home - SuperUser - Redbana Phils. Payroll</title>
<style type="text/css">
ul
{
list-style-type:none;
margin-left: 33%;
padding:0;
overflow:hidden;
}
li
{
  float:left;
  clear: left;
  width: 100px;
}
a:link,a:visited
{
display:block;
width:300px;
font-weight:bold;
color:#FFFFFF;
background-color:#98bf21;
text-align:center;
padding:4px;
text-decoration:none;
text-transform:uppercase;
}
a:hover,a:active
{
background-color:#7A991A;
}

</style><link href="<?php echo base_url(); ?>assets/css/mainstyling.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="header" class="center">
	<img src="<?php echo base_url(); ?>assets/images/payroll.png"  alt="header" />
</div>
<div id="header2" class="center">
	<p id="whatareyoudoing">Welcome 
		<?php
			echo $userData['empNum']."&nbsp;|&nbsp;".$userData['fname']." ".$userData['mname']."&nbsp;".$userData['sname']." ! ";
		?>		
	</p>
</div>
<!--
<div id="header2" class="center">
	<ul class="nav">
		<li class="nav"><a id="nav" href="<?php echo base_url(); ?>">Home</a></li>
	</ul>
</div>-->
<div id="container" class="center" >
<div id="article_SpecificDetail" class="center" style="width:80%">
	SuperUser Activities
</div>
<div style="width:80%" class="center">
	
	<ul>
		<li><a href="employee/getall" class="underline">Edit employee 
		information</a></li>
		<li><a href="#" class="underline">View payroll</a></li>
		<li><a href="sss/getall" class="underline">Edit SSS table</a></li>
		<li><a href="#" class="underline">Edit PhilHealth table</a></li>
		<li><a href="witholdingtaxcontroller" class="underline">Edit Witholding Tax Table</a></li>
		<li><a href="#" class="underline">View calendar</a></li>
		<li><a href="login/logout" class="underline">Sign out</a></li>
	</ul>
	<ul>
		<li><a href="maintenance/userview" class="underline">User Right Maintenance</a></li>
		<li><a href="maintenance/posview" class="underline">Position Maintenance</a></li>
		<li><a href="maintenance/taxview" class="underline">Tax Maintenance</a></li>
		<li><a href="maintenance/typeview" class="underline">Employment Maintenance</a></li>
	</ul>
	<ul>
		<li><a href="AttendanceController" class="underline">Absences and Tardiness</a></li>
	</ul>
	<ul>
		<li><a href="timesheet/viewtimesheet" class="underline">View TimeSheet</a></li>
	</ul>

</div>
</div>
<div id="copyright" >
<p>Copyright 2011 | Bautista and Associates Information Systems</p>
</div>

</body>

</html>
