<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!--

 REDBANA PHILS PAYROLL 
 For Practicum Purposes | CMSC 198 | summer 2011
 Generated by: Llave, Abraham Darius S. | 2008-37120
 
 FilePurpose: DesignFinal-1.0
 version: 1.0.0 - initial work
 		 
-->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>YOUR TITLE HERE Redbana Phils. Payroll</title>
<?php $this->load->view('include/css.inc'); ?>
<?php $this->load->view('include/jquery-abe.inc'); ?>
<?php $this->load->view('include/jquery-abe-on_run.inc'); ?>
</head>

<body>
<div id="main_container">
	<div id="header">
    	<div id="logo">
    	<a href="home.html"><img src="<?php echo base_url(); ?>assets/images/redbana_logo2.png" alt="" title="" style="border:0" /></a>    	
    	</div>
    	<div id="logo">
    	<a href="home.html"><img src="<?php echo base_url(); ?>assets/images/payroll_logo.jpg" alt="" title="" style="border:0" /></a>    	
    	</div>
        
         <div id="menu">
            <ul>                                        
                <li><a class="current" href="home.html" title="">Home</a></li>
				<li><a href="#" title="">My Account</a></li>
                <li><a href="#" title="">Edit Other Accounts</a></li>
                <li><a href="contact.html" title="">menu4</a></li>
            </ul>
        </div>
		<div id="graynavbar" >
			
			<ul>
				<li><?php echo $userData['empNum']; ?></li>
				<li><?php echo $userData['fname']." ".$userData['mname']."&nbsp;".$userData['sname']; ?></li>
				<li class="last">
					<a href='login/logout' class='underline'>Log out</a>
				</li>
			</ul>			
		</div>
        
    </div>
    
    <?php
		function can_Access($type,$query)
		{
			$result=false;
			foreach ($query->result() as $row)
			{
				if (($row->privilege ==$type) &&($row->type==1) )
				{
					$result=true;
					break;
				}
			}
			return $result;
		}
	?>
	
    
    <div id="main_content">    	
    	<div id="centralContainer">
            <!-- You place your html etc here -->
        </div><!--end of centralContainer-->
    <div style=" clear:both;"></div>
    </div><!--end of main content-->
 

     <div id="footer">
     	<div class="copyright">
			2011 UPLB Students
        </div>
    	<div class="footer_links"> 
        <a href="#">About us</a>
         <a href="privacy.html">Privacy policy</a> 
        <a href="contact.html">Contact us </a>        
        </div>        
    </div>     
<!--end of main container-->
</body>
</html>
